package tema_08;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAMJOR
 */
public class CalculadoraMini extends javax.swing.JFrame {

  /**
   * Creates new form CalculadoraMini
   */
  public CalculadoraMini() {
    initComponents();
    this.setLocationRelativeTo(CalculadoraMini.this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    txtResultado = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    txtOperando1 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtOperando2 = new javax.swing.JTextField();
    btnCalcular = new javax.swing.JButton();
    rbtSumar = new javax.swing.JRadioButton();
    rbtMultiplicar = new javax.swing.JRadioButton();
    lblError = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    txtResultado.setEditable(false);
    txtResultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    txtResultado.setText("0");

    jLabel1.setText("Operando1");

    txtOperando1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtOperando1.setText("0");

    jLabel2.setText("Operando2");

    txtOperando2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtOperando2.setText("0");
    txtOperando2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtOperando2ActionPerformed(evt);
      }
    });

    btnCalcular.setText("Calcular");
    btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        btnCalcularMousePressed(evt);
      }
    });
    btnCalcular.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCalcularActionPerformed(evt);
      }
    });

    buttonGroup1.add(rbtSumar);
    rbtSumar.setSelected(true);
    rbtSumar.setText("Sumar");
    rbtSumar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rbtSumarActionPerformed(evt);
      }
    });

    buttonGroup1.add(rbtMultiplicar);
    rbtMultiplicar.setText("Multiplicar");

    lblError.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(47, 47, 47)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(txtOperando2))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(txtOperando1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(rbtSumar)
                  .addComponent(rbtMultiplicar)))
              .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnCalcular))
          .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(57, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btnCalcular)
          .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txtOperando1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(rbtSumar))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtOperando2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(rbtMultiplicar))
        .addContainerGap(83, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtOperando2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOperando2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtOperando2ActionPerformed

 
  
  private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    // TODO add your handling code here:
    lblError.setText("");
    int operando1=0, operando2=0;
    
    try{
     operando1 = Integer.parseInt(txtOperando1.getText());
     operando2 = Integer.parseInt(txtOperando2.getText());
     int resultado;
      if (rbtSumar.isSelected())
        resultado = operar.suma(operando1, operando2);
      else
        resultado = operar.multiplicar(operando1, operando2);
    
        txtResultado.setText(String.valueOf(resultado));
     
    }catch (NumberFormatException ex){
      lblError.setText("Introducir sólo números");
    }
    
    int resultado;
    if (rbtSumar.isSelected())
      resultado = operar.suma(operando1, operando2);
    else
      resultado = operar.multiplicar(operando1, operando2);
    
    txtResultado.setText(String.valueOf(resultado));
      
    
  }//GEN-LAST:event_btnCalcularActionPerformed

  private void btnCalcularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMousePressed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCalcularMousePressed

  private void rbtSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSumarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_rbtSumarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CalculadoraMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CalculadoraMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CalculadoraMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CalculadoraMini.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new CalculadoraMini().setVisible(true);
      }
    });
  }
  
  Operar operar = new Operar();

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCalcular;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel lblError;
  private javax.swing.JRadioButton rbtMultiplicar;
  private javax.swing.JRadioButton rbtSumar;
  private javax.swing.JTextField txtOperando1;
  private javax.swing.JTextField txtOperando2;
  private javax.swing.JTextField txtResultado;
  // End of variables declaration//GEN-END:variables
}
