/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tema_08;

/**
 *
 * @author SAMJOR
 */
public class Practica_02 extends javax.swing.JFrame {

  /**
   * Creates new form Practica_02
   */
  public Practica_02() {
    initComponents();
    this.setLocationRelativeTo(Practica_02.this);
  }
  
  int k;

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jTextField5 = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextPane1 = new javax.swing.JTextPane();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    rbtMujer = new javax.swing.JRadioButton();
    rbtHombre = new javax.swing.JRadioButton();
    txtNombre = new javax.swing.JTextField();
    txtApellidos = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtEdad = new javax.swing.JFormattedTextField();
    txtAltura = new javax.swing.JFormattedTextField();
    txtPeso = new javax.swing.JFormattedTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    txaResultado = new javax.swing.JTextArea();
    btnCalcular = new javax.swing.JButton();
    btnLimpiar = new javax.swing.JButton();

    jTextField5.setText("jTextField5");

    jScrollPane2.setViewportView(jTextPane1);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Cálculo Peso Ideal");

    jLabel1.setText("Nombre");

    jLabel2.setText("Apellidos");

    jLabel3.setText("Edad:");

    buttonGroup1.add(rbtMujer);
    rbtMujer.setText("Mujer");
    rbtMujer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rbtMujerActionPerformed(evt);
      }
    });

    buttonGroup1.add(rbtHombre);
    rbtHombre.setSelected(true);
    rbtHombre.setText("Hombre");
    rbtHombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rbtHombreActionPerformed(evt);
      }
    });

    jLabel4.setText("Altura:");

    jLabel5.setText("Peso:");

    try {
      txtEdad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    try {
      txtAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    txtAltura.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtAlturaActionPerformed(evt);
      }
    });

    try {
      txtPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    txaResultado.setEditable(false);
    txaResultado.setColumns(20);
    txaResultado.setRows(5);
    jScrollPane1.setViewportView(txaResultado);

    btnCalcular.setText("Calcular");
    btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnCalcularMouseClicked(evt);
      }
    });

    btnLimpiar.setText("Limpiar");
    btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimpiarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(45, 45, 45)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(rbtHombre)
                  .addComponent(rbtMujer)))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(jScrollPane1))
            .addGap(33, 33, 33))
          .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(108, 108, 108)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(txtPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(46, 46, 46))))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnCalcular)
        .addGap(67, 67, 67)
        .addComponent(btnLimpiar)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rbtHombre)
          .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rbtMujer)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel4)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnCalcular)
            .addContainerGap())
          .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
    // TODO add your handling code here:
    
    String texto = ("\n"+"Nombre completo: "+txtNombre.getText()+" "+txtApellidos.getText()+"\n"
      +"Edad: "+txtEdad.getText()+ " años  "+"Altura: "+txtAltura.getText()+" cms   "+"Peso: "+txtPeso.getText()+" kgs "+"\n"
      +"IMC: "+calcularIMC()+"\n"
      +"Peso Ideal: "+pesoIdeal()+"\n");
    
    txaResultado.append(texto);
         
  }//GEN-LAST:event_btnCalcularMouseClicked

  private void rbtHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHombreActionPerformed
    // TODO add your handling code here:
    //int k=4;
  }//GEN-LAST:event_rbtHombreActionPerformed

  private void rbtMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMujerActionPerformed
    // TODO add your handling code here:
    //int k=2;
  }//GEN-LAST:event_rbtMujerActionPerformed

  private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtAlturaActionPerformed

  private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    // TODO add your handling code here:
    txtNombre.setText("");
    txtApellidos.setText("");
    txtEdad.setText("");
    txtAltura.setText("");
    txtPeso.setText("");
    rbtHombre.setSelected(true);
    txtNombre.requestFocus();
      
  }//GEN-LAST:event_btnLimpiarActionPerformed
// intenté hacer que cuando se pulsase sobre la casilla hombre o mujer, la variable k variara y tomara el valor 2 para
//  mujer y 4 para hombre, pero no supe cómo, así que le puse valor 3...
  protected String pesoIdeal(){
       int k=1;
       if (rbtHombre.isSelected())
         k=4;
       else if (rbtMujer.isSelected())
         k=2;
       double peso=(Double.parseDouble(txtAltura.getText()) - 100  
         - ((Double.parseDouble(txtAltura.getText())-150)/k));
       String cadena=String.format("%6.2f", peso);
       return cadena; 
    } 
  
  
  protected double calcularIMC(){
    double peso = Double.parseDouble(txtPeso.getText());
    double altura = Double.parseDouble(txtAltura.getText());
    double imc = peso/((altura/100)*(altura/100));
    return imc;
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Practica_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Practica_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Practica_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Practica_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Practica_02().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCalcular;
  private javax.swing.JButton btnLimpiar;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextPane jTextPane1;
  private javax.swing.JRadioButton rbtHombre;
  private javax.swing.JRadioButton rbtMujer;
  private javax.swing.JTextArea txaResultado;
  private javax.swing.JFormattedTextField txtAltura;
  private javax.swing.JTextField txtApellidos;
  private javax.swing.JFormattedTextField txtEdad;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JFormattedTextField txtPeso;
  // End of variables declaration//GEN-END:variables
}
